#!/bin/bash
# midi preprocessing
NTH=96
MAX_TRACK_NUMBER=32
MAX_DURATION=96
CONTINUING_NOTE=true
VELOCITY_STEP=16
TEMPO_MIN=24
TEMPO_MAX=200
TEMPO_STEP=16
POSITION_METHOD="attribute"
PROCESS_WORKERS=8
MIDI_DIR_PATH="data/midis/lmd_full"
MIDI_TO_TEXT_OTHER_ARGUMENTS="--make-stats"
DATA_NAME="lmd_full"
