#!/bin/bash
# midi preprocessing
NTH=96
MAX_TRACK_NUMBER=32
MAX_DURATION=96
VELOCITY_STEP=16
CONTINUING_NOTE=true
TEMPO_MIN=24
TEMPO_MAX=200
TEMPO_STEP=16
POSITION_METHOD="attribute"
PROCESS_WORKERS=8
MIDI_DIR_PATH="data/midis/SymphonyNet_Dataset"
DATA_NAME="snd"
