#!/bin/bash
# midi preprocessing
NTH=32
MAX_TRACK_NUMBER=24
MAX_DURATION=32
VELOCITY_STEP=128
CONTINUING_NOTE=false
USE_MERGE_DRUMS=true
TEMPO_MIN=24
TEMPO_MAX=200
TEMPO_STEP=16
POSITION_METHOD="event"
PROCESS_WORKERS=24
MIDI_DIR_PATH="data/midis/SymphonyNet_Dataset"
DATA_NAME="snd"
