#!/bin/bash
# midi preprocessing
NTH=96
MAX_TRACK_NUMBER=32
MAX_DURATION=96
VELOCITY_STEP=4
CONTINUING_NOTE=true
USE_MERGE_DRUMS=true
TEMPO_MIN=24
TEMPO_MAX=200
TEMPO_STEP=16
POSITION_METHOD="event"
PROCESS_WORKERS=1
MIDI_DIR_PATH="data/test_midis"
DATA_NAME="test_midis"
MIDI_TO_TEXT_VERBOSE=true

