#!/bin/bash
# midi preprocessing
NTH=32
MAX_TRACK_NUMBER=32
MAX_DURATION=32
VELOCITY_STEP=16
CONTINUING_NOTE=true
USE_MERGE_DRUMS=true
COMBINE_TRACK_INST=false
TEMPO_MIN=24
TEMPO_MAX=200
TEMPO_STEP=16
PROCESS_WORKERS=1
MIDI_DIR_PATH="data/test_midis"
DATA_NAME="test_midis"
MIDI_TO_CORPUS_VERBOSE=true

