#!/bin/bash
# midi preprocessing
NTH=96
MAX_TRACK_NUMBER=24
MAX_DURATION=4
VELOCITY_STEP=16
TEMPO_MIN=24
TEMPO_MAX=200
TEMPO_STEP=16
TEMPO_METHOD="position_event"
PROCESS_WORKERS=8
MIDI_DIR_PATH="data/midis/lmd_full/0"
MIDI_OTHER_ARGUMENTS="--make-stats"
PROC_DATA_NAME=lmd_small_nth${NTH}_r${MAX_TRACK_NUMBER}_d${MAX_DURATION}_v${VELOCITY_STEP}_t${TEMPO_MIN}_${TEMPO_MAX}_${TEMPO_STEP}

# make vocabulary
BPE_ITER=0
MAX_SAMPLE_LENGTH=1024
DATA_OTHER_ARGUMENTS='--debug'
