#!/bin/bash
# midi preprocessing
NTH=96
MAX_TRACK_NUMBER=32
MAX_DURATION=96
VELOCITY_STEP=8
TEMPO_MIN=24
TEMPO_MAX=200
TEMPO_STEP=16
POSITION_METHOD="event"
PROCESS_WORKERS=1
MIDI_DIR_PATH="data/test_midis"
MIDI_OTHER_ARGUMENTS="--verbose"
PROC_DATA_NAME="test_midis"

# text corpus and vocabulary
BPE_ITER=10
MAX_SAMPLE_LENGTH=1024
DATA_OTHER_ARGUMENTS='--debug'