#!/bin/bash
# midi preprocessing
NTH=96
MAX_TRACK_NUMBER=24
MAX_DURATION=4
VELOCITY_STEP=16
TEMPO_MIN=8
TEMPO_MAX=264
TEMPO_STEP=8
PROCESS_WORKERS=8
MIDI_DIR_PATH="data/midi"
ADDITIONAL_ARGUMENTS=""
PROCFILE_SUFFIX=nth${NTH}_r${MAX_TRACK_NUMBER}_d${MAX_DURATION}_v${VELOCITY_STEP}_t${TEMPO_MIN}-${TEMPO_MAX}-${TEMPO_STEP}

# make vocabulary
MAX_SAMPLE_LENGTH=4096
