#!/bin/bash
# midi preprocessing
NTH=96
MAX_TRACK_NUMBER=32
MAX_DURATION=96
VELOCITY_STEP=1
TEMPO_MIN=24
TEMPO_MAX=200
TEMPO_STEP=1
POSITION_METHOD="attribute"
PROCESS_WORKERS=1
MIDI_DIR_PATH="data/test_midis"
MIDI_OTHER_ARGUMENTS="--verbose --make-stats"
PROC_DATA_NAME=test_midis_pos_$POSITION_METHOD

# text corpus and vocabulary
BPE_ITER=4
SHAPECOUNT_SAMPLERATE=1.0
SHAPECOUNT_ALPHA=0.0
SHAPECOUNT_PRFTOPK=0
PROC_DATA_NAME_WITH_BPE=${PROC_DATA_NAME}_bpeiter${BPE_ITER}
MAX_SAMPLE_LENGTH=1024
DATA_OTHER_ARGUMENTS='--debug'