#!/bin/bash
# dataset parameters
MAX_SEQ_LENGTH=1024
SAMPLE_STRIDE=1
USE_PERMUTABL_SUBSEQ_LOSS=false
PERMUTE_MPS=false
PERMUTE_TRACK_NUMBER=false
MEASURE_NUMBER_SHIFT_RANGE=0

# model parameter
LAYERS_NUMBER=12
ATTN_HEADS_NUMBER=8
EMBEDDING_DIM=512

# training parameter
SPLIT_RATIO="8 2"
BATCH_SIZE=8
STEPS=100000
VALIDATION_INTERVAL=1000
LOG_HEAD_LOSSES=false
GRAD_NORM_CLIP=1.0
LEARNING_RATE=0.005
LEARNING_RATE_WARMUP_STEPS=4000
LEARNING_RATE_DECAY_END_STEPS=16000
LEARNING_RATE_DECAY_END_RATIO=0.5
EARLY_STOP=10

# others
USE_DEVICE='cpu'