#!/bin/bash
# dataset parameters
MAX_SEQ_LENGTH=256
SAMPLE_STRIDE=1
USE_PERMUTABLE_SUBSEQ_LOSS=false
PERMUTE_MPS=false
PERMUTE_TRACK_NUMBER=false

# model parameter
LAYERS_NUMBER=6
ATTN_HEADS_NUMBER=8
EMBEDDING_DIM=128
INPUT_NO_TEMPO=false
INPUT_NO_TIME_SIGNATURE=false

# training parameter
SPLIT_RATIO="199 1"
BATCH_SIZE=2
STEPS=100000
VALIDATION_INTERVAL=1000
LOG_HEAD_LOSSES=false
GRAD_NORM_CLIP=1.0
LEARNING_RATE=0.005
LEARNING_RATE_WARMUP_STEPS=4000
LEARNING_RATE_DECAY_END_STEPS=16000
LEARNING_RATE_DECAY_END_RATIO=0.5
EARLY_STOP=10

# others
USE_DEVICE='cuda'
