#!/bin/bash
# dataset parameters
MAX_SEQ_LENGTH=1024
SAMPLE_STRIDE=1
USE_PERMUTABL_SUBSEQ_LOSS=false
PERMUTE_MPS=false
PERMUTE_TRACK_NUMBER=false
MEASURE_NUMBER_SHIFT_RANGE=0

# model parameter
LAYERS_NUMBER=1
ATTN_HEADS_NUMBER=2
EMBEDDING_DIM=32

# training parameter
SPLIT_RATIO="8 2"
BATCH_SIZE=8
STEPS=1000
VALIDATION_INTERVAL=40
LOG_HEAD_LOSSES=true
GRAD_NORM_CLIP=1.0
LEARNING_RATE=0.005
LEARNING_RATE_WARMUP_STEPS=40
LEARNING_RATE_DECAY_END_STEPS=160
LEARNING_RATE_DECAY_END_RATIO=0.5
EARLY_STOP=10

# others
USE_DEVICE='cpu'